spring:
  application:
    name: lms-lti-courselist
  profiles:
    active: redis
  session:
    store-type: none
#  output:
#    ansi:
#      enabled: ALWAYS
security:
  oauth2:
    resource:
      jwt:
        key-uri: ${oauth.tokenprovider.url}/oauth/token_key
courselist:
  version: ${app.version}
  env: ${app.env}
  startANewCourseUrl: /users/self/external_tools/100230

---

spring:
  profiles: redis
  session:
    store-type: redis
    redis.namespace: courselist-${app.version}:session